# Generated by Django 2.2.24 on 2025-01-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseMate', '0004_auto_20250112_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='date',
        ),
    ]
